import { randomUUID } from "node:crypto";
import path from "node:path";
import { TextDecoder } from "node:util";
import { DeleteObjectCommand, PutObjectCommand } from "@aws-sdk/client-s3";
import prisma from "../config/prisma.js";
import s3Client from "../config/s3.js";
import { env } from "../config/env.js";
import { MAX_DOCUMENT_SIZE_BYTES } from "../utils/documentLimits.js";
import { enqueueDocumentProcessing } from "./documentQueueService.js";

const ALLOWED_MIME_TYPES = new Set(["application/pdf", "text/plain"]);

export class DocumentServiceError extends Error {
  constructor(statusCode, message) {
    super(message);
    this.name = "DocumentServiceError";
    this.statusCode = statusCode;
  }
}

function parseDocumentId(value) {
  const documentId = Number(value);
  if (
    typeof value !== "string" || !/^\d+$/.test(value) ||
    !Number.isSafeInteger(documentId) || documentId <= 0 || documentId > 2_147_483_647
  ) {
    throw new DocumentServiceError(400, "documentId must be a positive integer");
  }
  return documentId;
}

function normalizedFilename(value) {
  if (typeof value !== "string") throw new DocumentServiceError(400, "A valid filename is required");
  // Handle both Unix and Windows paths even if a multipart client sends one.
  const base = path.posix.basename(path.win32.basename(value)).replace(/[\u0000-\u001f\u007f]/g, "").trim();
  if (!base || base === "." || base === ".." || Array.from(base).length > 255) {
    throw new DocumentServiceError(400, "A valid filename of at most 255 characters is required");
  }
  return base;
}

function keyFilename(fileName) {
  const extension = path.extname(fileName).toLowerCase().replace(/[^a-z0-9.]/g, "").slice(0, 16);
  const stem = path.basename(fileName, path.extname(fileName))
    .normalize("NFKD").replace(/[^a-zA-Z0-9_-]+/g, "-").replace(/^-+|-+$/g, "")
    .slice(0, 80) || "document";
  return `${stem}${extension}`;
}

function validateFile(file) {
  if (!file) throw new DocumentServiceError(400, "A document file is required");
  if (!Buffer.isBuffer(file.buffer) || file.buffer.length === 0) {
    throw new DocumentServiceError(400, "Document file cannot be empty");
  }
  if (file.buffer.length > MAX_DOCUMENT_SIZE_BYTES) {
    throw new DocumentServiceError(413, "Document must not exceed 10 MB");
  }
  if (!ALLOWED_MIME_TYPES.has(file.mimetype)) {
    throw new DocumentServiceError(400, "Only PDF and plain-text documents are supported");
  }

  if (file.mimetype === "application/pdf" && !file.buffer.subarray(0, 5).equals(Buffer.from("%PDF-"))) {
    throw new DocumentServiceError(400, "Uploaded file is not a valid PDF document");
  }
  if (file.mimetype === "text/plain") {
    try {
      new TextDecoder("utf-8", { fatal: true }).decode(file.buffer);
    } catch {
      throw new DocumentServiceError(400, "Plain-text documents must contain valid UTF-8 text");
    }
    if (file.buffer.includes(0)) {
      throw new DocumentServiceError(400, "Uploaded file is not a valid plain-text document");
    }
  }
  return normalizedFilename(file.originalname);
}

const safeDocumentSelect = {
  id: true,
  organizationId: true,
  fileName: true,
  mimeType: true,
  status: true,
  createdAt: true,
  updatedAt: true,
};

function storageConfiguration(overrides = {}) {
  const bucket = overrides.bucket ?? env.awsS3Bucket;
  const client = overrides.client ?? s3Client;
  if (!env.awsRegion || !bucket) {
    throw new DocumentServiceError(503, "Document storage is not configured");
  }
  return { bucket, client };
}

export async function uploadDocument(organizationId, file, storageOverrides) {
  const fileName = validateFile(file);
  const { bucket, client } = storageConfiguration(storageOverrides);
  const storageKey = `organizations/${organizationId}/documents/${randomUUID()}-${keyFilename(fileName)}`;

  try {
    await client.send(new PutObjectCommand({
      Bucket: bucket,
      Key: storageKey,
      Body: file.buffer,
      ContentType: file.mimetype,
    }));
  } catch (error) {
    console.error("S3 document upload failed", error);
    throw new DocumentServiceError(502, "Document upload failed");
  }

  let document;
  try {
    document = await prisma.document.create({
      data: {
        organizationId,
        fileName,
        mimeType: file.mimetype,
        storageKey,
        status: "PENDING",
      },
      select: safeDocumentSelect,
    });
  } catch (error) {
    // S3 and MySQL are not atomic. Delete only the key generated by this request.
    try {
      await client.send(new DeleteObjectCommand({ Bucket: bucket, Key: storageKey }));
    } catch (cleanupError) {
      console.error("S3 cleanup failed after document metadata error", cleanupError);
    }
    console.error("Document metadata creation failed", error);
    throw new DocumentServiceError(500, "Unable to save document metadata");
  }

  try {
    await enqueueDocumentProcessing(
      { documentId: document.id, organizationId },
      {
        client: storageOverrides?.sqsClient,
        queueUrl: storageOverrides?.queueUrl,
        region: storageOverrides?.region,
      },
    );
    return document;
  } catch (error) {
    console.error("Document queue publish failed", error);
    let metadataCompensated = false;
    try {
      await prisma.document.deleteMany({
        where: { id: document.id, organizationId, storageKey },
      });
      metadataCompensated = true;
    } catch (cleanupError) {
      // Keep the exact S3 object when metadata deletion is uncertain so the row
      // cannot be left pointing at an object that this request removed.
      console.error("Document metadata cleanup failed after queue error", cleanupError);
    }

    if (metadataCompensated) {
      try {
        await client.send(new DeleteObjectCommand({ Bucket: bucket, Key: storageKey }));
      } catch (cleanupError) {
        console.error("S3 cleanup failed after queue error", cleanupError);
      }
    }
    throw new DocumentServiceError(502, "Document processing could not be queued");
  }
}

export async function listDocuments(organizationId) {
  return prisma.document.findMany({
    where: { organizationId },
    select: safeDocumentSelect,
    orderBy: [{ createdAt: "desc" }, { id: "desc" }],
  });
}

export async function getDocument(organizationId, rawDocumentId) {
  const documentId = parseDocumentId(rawDocumentId);
  const document = await prisma.document.findFirst({
    where: { id: documentId, organizationId },
    select: safeDocumentSelect,
  });
  if (!document) throw new DocumentServiceError(404, "Document not found");
  return document;
}
